version: 2.1

orbs:
  node: circleci/node@2.1.1

jobs:
  publish:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - run:
          name: Set npm credentials
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" >> ~/.npmrc
      - node/install-packages
      - run:
          name: Publish to npm
          command: npm run publish-please

workflows:
  version: 2

  test-and-publish:
    jobs:
      - node/test:
          version: 'lts'
          filters:
            tags:
              only: /.*/
      - publish:
          context: manwaring-npm
          requires: [node/test]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
